# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('users', models.ManyToManyField(related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
