# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='places', to='authentication.User'),
        ),
    ]
