# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20170316_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='picture',
            field=models.ImageField(default='default/place.jpg', upload_to='places'),
        ),
    ]
