# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='place',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='pots', to='places.Place'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='plant',
            field=models.ForeignKey(blank=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='pots', to='plants.Plant'),
        ),
    ]
