# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0002_pot_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeserie',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
