# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0003_auto_20170316_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('label', models.CharField(default='', max_length=250, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.Action')),
            ],
        ),
        migrations.AlterField(
            model_name='pot',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pots', to='places.Place'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pots', to='plants.Plant'),
        ),
        migrations.AlterField(
            model_name='timeserie',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='pots.Pot'),
        ),
        migrations.AddField(
            model_name='operation',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='pots.Pot'),
        ),
    ]
